In [67]:
!pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (4.5.0)
Requirement already satisfied: filelock in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (4.68.3)
Requirement already satisfied: xxhash in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.19 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from httpx<1.0.0->datasets) (3.16)
Requirement already satisfied: h11>=0.16 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.15.0)

from datasets import load_dataset

In [68]:
from datasets import load_dataset
import pandas as pd

from arxiv site(contains research papers and need to find which one is relevant)only searching by title in not relevant, title + extract sematic analysis is helpful for relevancy

https://huggingface.co/datasets/CShorten/ML-ArXiv-Papers

in dataset its 4 columns two unnamed and one title and other extract

In [69]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')

In [70]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [71]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

dataset is not proper (in form of key value )we have to frame it

In [72]:
df=pd.DataFrame(dataset)

In [73]:
df

        Unnamed: 0.1  ...                                           abstract
0                  0  ...    The problem of statistical learning is to co...
1                  1  ...    In a sensor network, in practice, the commun...
2                  2  ...    The on-line shortest path problem is conside...
3                  3  ...    Ordinal regression is an important type of l...
4                  4  ...    This paper uncovers and explores the close r...
...              ...  ...                                                ...
117587          4995  ...  The sharing of fake news and conspiracy theori...
117588          4996  ...  The feature subset selection problem aims at s...
117589          4997  ...  We present a short and elementary proof of the...
117590          4998  ...  We introduce CoLN, Combined Learning of Neural...
117591          4999  ...  Influence estimation analyzes how changes to t...

[117592 rows x 4 columns]

In [74]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [75]:
df=df[['title','abstract']]

In [76]:
df

                                                    title                                           abstract
0                   Learning from compressed observations    The problem of statistical learning is to co...
1       Sensor Networks with Random Links: Topology De...    In a sensor network, in practice, the commun...
2       The on-line shortest path problem under partia...    The on-line shortest path problem is conside...
3         A neural network approach to ordinal regression    Ordinal regression is an important type of l...
4        Parametric Learning and Monte Carlo Optimization    This paper uncovers and explores the close r...
...                                                   ...                                                ...
117587  Detecting COVID-19 Conspiracy Theories with Tr...  The sharing of fake news and conspiracy theori...
117588  Fair Feature Subset Selection using Multiobjec...  The feature subset selection problem aims at s...
117589  A Simple Duality Proof for Wasserstein Distrib...  We present a short and elementary proof of the...
117590  Combined Learning of Neural Network Weights fo...  We introduce CoLN, Combined Learning of Neural...
117591  Adapting and Evaluating Influence-Estimation M...  Influence estimation analyzes how changes to t...

[117592 rows x 2 columns]

In [77]:
df.shape

(117592, 2)

title+abstract for this is much data is quite huge

sir taking 15000 dataset for easy processing but we can take full

In [78]:
df=df.head(15000)

In [79]:
df.shape

(15000, 2)

for every dataset embedding is done,11700*4 (int type) byte is quite huge

In [80]:
df["paper_text"]=df["title"]+" "+df["abstract"]

/var/folders/c8/1gw1zkyj50z2jdyb3mltt0lw0000gn/T/ipykernel_25535/529180721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

In [81]:
df.isnull().sum()

title         0
abstract      0
paper_text    0
dtype: int64

In [82]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [83]:
type(df["paper_text"])

pandas.core.series.Series

In [84]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

implementing sentence transformer

In [85]:

%pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (5.1.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.57.6)
Requirement already satisfied: tqdm in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.68.3)
Requirement already satisfied: torch>=1.11.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: scikit-learn in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (0.36.2)
Requirement already satisfied: Pillow in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2026.1.15)
Requirement already satisfied: requests in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.1)
Requirement already satisfied: sympy>=1.13.3 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.16)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: joblib>=1.2.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [90]:
try:
    model = SentenceTransformer("all-MiniLM-L6-v2")
except Exception as e:
    print("Failed to load 'all-MiniLM-L6-v2':", e)
    try:
        # fallback: explicit repo id and force CPU (useful if CUDA/torch issues)
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device="cpu")
        print("Loaded fallback model on CPU")
    except Exception as e2:
        print("Fallback load failed:", e2)
        raise

'[Errno 8] nodename nor servname provided, or not known' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 1s [Retry 1/5].
'[Errno 8] nodename nor servname provided, or not known' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 1s [Retry 1/5].

Failed to load 'all-MiniLM-L6-v2': Cannot send a request, as the client has been closed.
Fallback load failed: Cannot send a request, as the client has been closed.
Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/var/folders/c8/1gw1zkyj50z2jdyb3mltt0lw0000gn/T/ipykernel_25535/87296366.py", line 2, in <module>
    model = SentenceTransformer("all-MiniLM-L6-v2")
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/SentenceTransformer.py", line 327, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/SentenceTransformer.py", line 2305, in _load_sbert_model
    module = module_class.load(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 365, in load
    return cls(model_name_or_path=model_name_or_path, **init_kwargs)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 87, in __init__
    config, is_peft_model = self._load_config(model_name_or_path, cache_dir, backend, config_args)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 138, in _load_config
    find_adapter_config_file(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/peft_utils.py", line 88, in find_adapter_config_file
    adapter_cached_filename = cached_file(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 322, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 479, in cached_files
    hf_hub_download(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    If an input is not valid.
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 986, in hf_hub_download
    warnings.warn(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1119, in _hf_hub_download_to_cache_dir
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1653, in _get_metadata_or_catch_error
    raise LocalEntryNotFoundError(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    If an input is not valid.
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1576, in get_hf_file_metadata
    )
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 685, in _httpx_follow_relative_redirects_with_backoff
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 559, in http_backoff
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 467, in _http_backoff_base
    raise _format(HfHubHTTPError, message, response) from e
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 901, in send
    raise RuntimeError("Cannot send a request, as the client has been closed.")
RuntimeError: Cannot send a request, as the client has been closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/c8/1gw1zkyj50z2jdyb3mltt0lw0000gn/T/ipykernel_25535/87296366.py", line 7, in <module>
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device="cpu")
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/SentenceTransformer.py", line 327, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/SentenceTransformer.py", line 2305, in _load_sbert_model
    module = module_class.load(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 365, in load
    return cls(model_name_or_path=model_name_or_path, **init_kwargs)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 87, in __init__
    config, is_peft_model = self._load_config(model_name_or_path, cache_dir, backend, config_args)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/sentence_transformers/models/Transformer.py", line 138, in _load_config
    find_adapter_config_file(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/peft_utils.py", line 88, in find_adapter_config_file
    adapter_cached_filename = cached_file(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 322, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/transformers/utils/hub.py", line 479, in cached_files
    hf_hub_download(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    If an input is not valid.
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 986, in hf_hub_download
    warnings.warn(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1119, in _hf_hub_download_to_cache_dir
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1653, in _get_metadata_or_catch_error
    raise LocalEntryNotFoundError(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    If an input is not valid.
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/file_download.py", line 1576, in get_hf_file_metadata
    )
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 685, in _httpx_follow_relative_redirects_with_backoff
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 559, in http_backoff
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_http.py", line 467, in _http_backoff_base
    raise _format(HfHubHTTPError, message, response) from e
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 901, in send
    raise RuntimeError("Cannot send a request, as the client has been closed.")
RuntimeError: Cannot send a request, as the client has been closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/Users/sanchaysingla/Library/Python/3.9/lib/python/site-packages/executing/executing.py", line 76, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

In [89]:
print(type(model))

NameError: name 'model' is not defined

when we create embedding ,we have to do nlp preprocessing technique

stop word removal,tokenization

In [ ]:
sample_text=df['paper_text'].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

we have to replace /n as transformer can get confused

In [ ]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/var/folders/c8/1gw1zkyj50z2jdyb3mltt0lw0000gn/T/ipykernel_25535/759125261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)

In [ ]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

NameError: name 'model' is not defined