AI RESEARCH PAPER ASSISTANT AND **SEGREGATOR** bold text

# 1. Environment Setup

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

## 1.1 Import Libraries

from datasets import load_dataset

In [2]:
from datasets import load_dataset
import pandas as pd

# 2. Data Loading and Preprocessing

from arxiv site(contains research papers and need to find which one is relevant)only searching by title in not relevant, title + extract sematic analysis is helpful for relevancy

https://huggingface.co/datasets/CShorten/ML-ArXiv-Papers

in dataset its 4 columns two unnamed and one title and other extract

## 2.1 Load Dataset

In [3]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

## 2.2 Initial Data Inspection and Cleaning

dataset is not proper (in form of key value )we have to frame it

In [6]:
df=pd.DataFrame(dataset)

In [7]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df=df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

## 2.3 Sampling Data for Easier Processing

In [11]:
df.shape

(117592, 2)

title+abstract for this is much data is quite huge

sir taking 15000 dataset for easy processing but we can take full

In [12]:
df=df.head(15000)

In [13]:
df.shape

(15000, 2)

## 2.4 Combine Title and Abstract

for every dataset embedding is done,11700*384 (int type) byte is quite huge

In [14]:
df["paper_text"]=df["title"]+" "+df["abstract"]

/tmp/ipykernel_2862/529180721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

In [15]:
df.isnull().sum()

title         0
abstract      0
paper_text    0
dtype: int64

In [16]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

## 2.5 Text Cleaning

In [17]:
type(df[["paper_text"]])

pandas.core.frame.DataFrame

In [18]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

implementing sentence transformer

In [19]:

from sentence_transformers import SentenceTransformer

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

## 3.1 Load Sentence Transformer Model

In [20]:
model = SentenceTransformer("all-MiniLM-L6-v2")

## 3.2 Generate and Inspect Sample Embeddings

In [21]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

when we create embedding ,we have to do nlp preprocessing technique

stop word removal,tokenization

In [22]:
sample_text=df['paper_text'].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

we have to replace /n as transformer can get confused

In [23]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_2862/2190359946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
/tmp/ipykernel_2862/2190359946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

# 3. Sentence Embeddings for Semantic Search

In [24]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [25]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

# 4. Similarity Search with FAISS

In [26]:
sample_embedding=model.encode(df["paper_text"].head(5).to_list())

In [27]:
print(sample_embedding.shape)

(5, 384)

## 4.1 Cosine Similarity Introduction

SUGGESTION LIKE SERACHING FOR AUTOMOBILE AND RESEARCH PAPER CONTAINS CONTENT OF CAR AND BEHICLES SO SEMANTICALLY THEY ARE SAME

COSINE SIMILARITY (A.B/|A|.|B|)

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
'''similarity=cosine_similarity(sample_embedding[0],sample_embedding[0])'''

'similarity=cosine_similarity(sample_embedding[0],sample_embedding[0])'

cosine similarity expect 2d data,sample_embedding[0] has single embedding with [,384] but i should have one row and all names

reshape[1,-1] will take 1 row and adjust column to toal shapes

## 4.2 Demonstrating Cosine Similarity

eg [5,6]-->[5,6*5]=[5,30][

In [30]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))

In [31]:
print(similarity)

[[1.0000001]]

In [32]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))

In [33]:
print(similarity)

[[0.36625272]]

## 4.3 Generating Embeddings for Entire Dataset

In [34]:
for i in range(1,5):
  sin=similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
  print(sin)

[[0.36625272]]
[[0.36625272]]
[[0.36625272]]
[[0.36625272]]

GENERATION OF ALL 15000 PAPERS

In [35]:
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings

## 4.4 FAISS Index Creation

In [36]:
print(embedding.shape)
print(type(embedding))

(384,)
<class 'numpy.ndarray'>

In [37]:
embedding.dtype

dtype('float32')

FAISS~Facebook AI similarity search
(Vector database)

create a structure which can ease the process of search

build search structure for speed

internal structure with index creation on the top of the embedding

In [38]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [39]:
import faiss

## 4.5 Build and Save FAISS Index

In [40]:
import numpy as np

In [41]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)
    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index

## 4.6 Testing the FAISS Index

for creating index first we normalized embedding,faiss creates structure flat creates same (neither compressed nor approxiamation),stores all the vectors,IP stands for innner product of all embeddings

above is just a function,but no passing of embedding

In [42]:
print(index.ntotal)

15000

In [43]:
query="deeep learning for medical image analysis"

In [44]:
query_embedding=model.encode(query)

In [45]:
query_embedding.shape

(384,)

In [46]:
query_embedding.reshape(1,-1)

array([[-8.91347881e-03,  4.24088500e-02,  3.96373235e-02,
        -8.75462294e-02, -4.33073239e-03, -9.53942016e-02,
         1.32165462e-01,  2.11447030e-02,  1.33173913e-02,
        -2.14715768e-03, -3.48479562e-02, -3.11603323e-02,
         2.90877558e-03,  5.49279116e-02, -8.22757334e-02,
        -1.32649997e-02, -1.17033020e-01, -1.47760464e-02,
        -3.85108143e-02,  5.51063344e-02, -5.35834655e-02,
         3.18396762e-02, -5.36726043e-02, -3.92478444e-02,
         3.43137011e-02,  2.04335582e-02,  6.49864376e-02,
         8.85641202e-03,  3.40326056e-02, -5.88501580e-02,
         4.21522669e-02,  3.36007308e-03, -5.37609216e-03,
        -1.55146541e-02,  2.37983558e-02,  1.27095738e-02,
         2.42141355e-02,  5.71320504e-02, -3.86737250e-02,
         1.07356057e-01,  3.09558789e-04,  6.11782297e-02,
        -3.49811949e-02, -2.42499020e-02,  7.20748976e-02,
        -1.52707947e-02, -2.86656488e-02, -5.77483997e-02,
         3.77038755e-02,  5.24876490e-02, -2.51735039e-02,
         9.11839027e-03, -9.26690474e-02,  5.22838756e-02,
         3.79766636e-02, -1.93331894e-02,  9.92558338e-03,
        -5.87956905e-02, -5.07017970e-02, -5.92770167e-02,
        -3.79129611e-02, -2.32417714e-02, -2.86478130e-03,
         2.38718502e-02,  8.99399891e-02,  2.85477232e-04,
         3.69373038e-02,  4.39112149e-02, -3.02477051e-02,
        -3.38671021e-02, -5.25500104e-02,  7.06917001e-03,
        -1.45581728e-02,  1.10370085e-01, -1.17722116e-02,
        -4.35478054e-03,  8.33056793e-02,  5.90691790e-02,
         4.70418409e-02, -1.48630723e-01,  4.99089509e-02,
         3.64279598e-02,  4.49196175e-02, -3.68006229e-02,
         6.59784824e-02,  8.02689977e-03, -1.54658174e-02,
         4.83388640e-02, -5.94655052e-02,  1.50020961e-02,
         9.24679935e-02,  4.77163829e-02, -7.61411041e-02,
        -2.15525590e-02,  3.07847504e-02,  1.29980147e-02,
        -2.51475573e-02, -2.56987158e-02,  2.40005255e-02,
         1.05949156e-01, -2.00104173e-02, -9.50754955e-02,
        -4.08992432e-02,  3.44814174e-02, -2.77879485e-03,
        -5.56139648e-02,  9.21841860e-02, -6.37103096e-02,
         9.08769146e-02, -1.00020565e-01,  6.71166694e-03,
         3.77071882e-03, -3.06809670e-04,  3.73037085e-02,
         1.76052321e-02, -1.50285615e-02,  1.27018401e-02,
        -1.98680311e-02,  9.66152176e-02, -7.70730227e-02,
        -3.24667841e-02, -4.51525114e-02, -2.56021619e-02,
        -3.49618495e-02,  9.45469439e-02, -5.84932007e-02,
        -1.08788341e-01, -2.06123008e-33,  6.19141199e-02,
         2.69474369e-03,  5.20791262e-02, -4.27677706e-02,
        -3.27207856e-02, -4.06701453e-02, -8.15197732e-03,
         9.13923047e-03,  4.53080516e-03,  5.24654463e-02,
        -8.03906762e-04,  6.81254491e-02, -5.63771427e-02,
         5.57769649e-02,  4.86815087e-02, -2.44336911e-02,
         1.76894628e-02,  8.06952715e-02, -1.38225183e-02,
         3.10760480e-03,  6.99094776e-03, -6.89257383e-02,
        -4.21751924e-02, -1.03410874e-02, -8.25469792e-02,
         4.51906845e-02, -9.32258274e-03,  1.12848449e-02,
         8.93114135e-02,  2.45750789e-02, -1.06852964e-01,
         9.47940722e-03, -2.91744415e-02,  2.01105122e-02,
         3.29396911e-02,  4.46364004e-03, -2.57375501e-02,
         6.50500208e-02,  4.32008803e-02, -1.51683437e-02,
        -1.67734977e-02,  2.97180749e-02,  5.85214347e-02,
        -9.95395556e-02, -1.79634187e-02,  1.26431420e-01,
         2.63966527e-02, -4.49863933e-02, -5.35414405e-02,
        -7.73423091e-02,  5.35413809e-03, -1.19911857e-01,
         2.09903326e-02, -4.12110891e-03,  2.44828742e-02,
         5.88927306e-02, -1.00758299e-01,  1.52620254e-02,
         4.37826626e-02, -1.56972185e-02,  5.23285717e-02,
         8.90280586e-03,  2.09803786e-02,  2.79042125e-03,
         1.81165356e-02, -2.50691362e-02, -6.54952005e-02,
         2.11426504e-02,  4.36710194e-02, -4.28333879e-03,
        -7.34064803e-02,  9.83565375e-02, -3.84391882e-02,
        -8.52336958e-02,  2.80415043e-02,  5.61298691e-02,
         4.58148420e-02,  3.31916660e-02, -3.40679586e-02,
        -3.52048390e-02, -4.26787604e-03,  1.82960462e-02,
         8.08787905e-03, -1.03421777e-01, -2.32220683e-02,
        -1.00750970e-02,  9.16867107e-02, -2.39251880e-04,
        -1.15392946e-01, -3.32771130e-02, -1.14423983e-01,
         8.69615600e-02, -1.08020278e-02, -4.75535244e-02,
        -5.46752810e-02,  1.42692800e-33, -2.74025393e-03,
         1.07182622e-01, -1.31810270e-02, -2.98047792e-02,
         1.97881516e-02,  2.54100561e-02, -1.39751248e-02,
         7.60704800e-02,  2.39705164e-02, -1.50090242e-02,
         8.35683793e-02,  1.73928204e-03, -5.30146696e-02,
        -7.63614476e-02, -6.92570284e-02, -8.51538498e-03,
        -5.89652099e-02, -6.21045269e-02, -1.66126508e-02,
         1.03390124e-02, -9.22446046e-03,  9.02307034e-02,
        -4.98483516e-02,  2.74278708e-02, -1.06706135e-01,
         3.98316830e-02,  2.02536415e-02,  3.56903337e-02,
        -6.09937403e-03, -2.22758614e-02, -2.26223562e-02,
        -4.82037067e-02, -2.91498546e-02, -2.12656781e-02,
        -4.50955667e-02,  5.70982229e-03,  1.31499162e-02,
        -1.33475987e-02, -6.41449634e-03,  4.79025990e-02,
         3.98865677e-02, -3.39523330e-02, -5.42480424e-02,
        -4.56676865e-03,  3.75431217e-02, -7.42883459e-02,
        -4.59437771e-03,  2.98321024e-02,  5.69330975e-02,
         7.84918517e-02, -3.19068916e-02, -2.07140134e-03,
        -1.11766560e-02,  9.66421515e-03, -9.45088714e-02,
        -3.76453996e-02,  1.91786457e-02, -1.65543985e-02,
         1.60964578e-02, -1.28538138e-03, -8.79200399e-02,
        -8.34368989e-02, -6.51730970e-02,  3.51478858e-03,
        -2.28626002e-02,  6.68672621e-02, -5.63311996e-03,
        -5.49119990e-03, -4.27204110e-02,  9.56838429e-02,
        -2.55765971e-02,  6.12994358e-02, -4.06455770e-02,
        -9.38488729e-03,  4.54729684e-02, -7.11261779e-02,
         8.64051003e-03, -3.58499102e-02,  1.45085109e-03,
         2.60067917e-02,  6.12089597e-02, -1.11784682e-01,
         9.86563042e-03,  9.62361023e-02, -4.54498865e-02,
         1.06729157e-01,  3.36113051e-02, -1.35296553e-01,
         2.79482342e-02, -7.97553286e-02, -4.04734574e-02,
         2.63100192e-02,  3.90633307e-02,  1.29614156e-02,
        -3.75689976e-02, -1.44162424e-08, -1.82213094e-02,
        -3.30588669e-02,  5.51541299e-02, -1.06062610e-02,
         4.92583669e-04, -4.12253439e-02, -5.20252846e-02,
         7.39064142e-02, -2.62994040e-02,  6.03587413e-03,
        -8.39420408e-03,  2.69670933e-02, -7.53334984e-02,
        -5.87602369e-02,  5.95811233e-02,  8.12243596e-02,
         4.91884798e-02,  6.44762069e-02, -8.33962485e-03,
        -1.93238743e-02,  1.85987037e-02, -2.85953470e-03,
         4.43346575e-02,  2.67059114e-02,  3.10270414e-02,
        -5.75293265e-02, -2.08220091e-02, -8.16754103e-02,
         2.99859345e-02, -9.32550523e-03,  5.52159473e-02,
         1.13152362e-01,  8.75025094e-02,  4.73301206e-03,
         1.08479351e-01,  2.92508746e-03, -3.21336254e-03,
        -1.98158920e-02, -4.94455732e-02,  2.02285741e-02,
         2.64834650e-02,  5.07959984e-02, -4.59996425e-03,
        -6.14774823e-02, -3.79853100e-02,  3.98573279e-03,
         9.35300291e-02,  3.49723659e-02,  2.53330581e-02,
         1.48672964e-02,  3.28980759e-02,  7.32950540e-03,
         5.01003973e-02,  1.77881699e-02,  3.79370600e-02,
         1.95370540e-02,  8.95092413e-02, -2.83447653e-02,
         2.85359356e-03,  9.37955007e-02,  4.58033532e-02,
        -5.30150300e-03, -3.45051265e-03,  1.75776463e-02]], dtype=float32)

## 4.7 Define Search Function

In [47]:
query_embedding.shape

(384,)

In [48]:
query_embedding_final=model.encode([query])
query_embedding_final.shape

(1, 384)

In [49]:
faiss.normalize_L2(query_embedding_final)

In [50]:
D,I=index.search(query_embedding_final,5)
print(D)
print(I)

[[0.5202042  0.51973665 0.504279   0.5003392  0.49550495]]
[[10466  5544 13730  8852  7426]]

this will give similarity score and seach index (give relevant 5 researches)

In [51]:
df.iloc[10466]["title"]

'A Perspective on Deep Imaging'

In [52]:
df.iloc[11873]["title"]

'Classification of MRI data using Deep Learning and Gaussian\n  Process-based Model Selection'

here mri means semantic meaning gapp reduce due sentence transformers

In [53]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()

# 5. Summarization with BART

In [54]:
search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

BART (bidirectional transformer with both encoder and decoder)

## 5.1 Load Summarization Pipeline

In [55]:
!pip install transformers==4.51.3

Requirement already satisfied: transformers==4.51.3 in /usr/local/lib/python3.12/dist-packages (4.51.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.3) (2026.6.17)

In [56]:
from transformers import pipeline

In [57]:
summarizer=pipeline("summarization",model="facebook/bart-large-cnn")

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

## 5.2 Test Summarization

In [58]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [59]:
summary=summarizer

In [60]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [61]:
type(summary)

list

In [62]:
type(summary[0])

dict

In [63]:
summary[0]["summary_text"]

'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'

## 5.3 Integrate Summarization into Search

In [64]:
for score,idx in zip(D[0],I[0]):
  print("Similarity score",score)
  print("Title",df.iloc[idx]["title"])
  print("Abstract",df.iloc[idx]["abstract"][:500])
  summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
  print (summary)
  print(summary[0]["summary_text"])
  print()

Similarity score 0.5202042
Title A Perspective on Deep Imaging
Abstract   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.51973665
Title Machine Learning for Neuroimaging with Scikit-Learn
Abstract   Statistical machine learning methods are increasingly used for neuroimaging
data analysis. Their main virtue is their ability to model high-dimensional
datasets, e.g. multivariate analysis of activation images or resting-state time
series. Supervised learning is typically used in decoding or encoding settings
to relate brain images to behavioral or clinical observations, while
unsupervised learning can uncover hidden structures in sets of images (e.g.
resting state functional MRI) or find sub-
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.504279
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.5003392
Title Variational Autoencoders for Feature Detection of Magnetic Resonance
  Imaging Data
Abstract   Independent component analysis (ICA), as an approach to the blind
source-separation (BSS) problem, has become the de-facto standard in many
medical imaging settings. Despite successes and a large ongoing research
effort, the limitation of ICA to square linear transformations have not been
overcome, so that general INFOMAX is still far from being realized. As an
alternative, we present feature analysis in medical imaging as a problem solved
by Helmholtz machines, which include dimensionality re
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.49550495
Title Evaluation of Joint Multi-Instance Multi-Label Learning For Breast
  Cancer Diagnosis
Abstract   Multi-instance multi-label (MIML) learning is a challenging problem in many
aspects. Such learning approaches might be useful for many medical diagnosis
applications including breast cancer detection and classification. In this
study subset of digiPATH dataset (whole slide digital breast cancer
histopathology images) are used for training and evaluation of six
state-of-the-art MIML methods.
  At the end, performance comparison of these approaches are given by means of
effective evaluation metr
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

# 6. Keyword Extraction with KeyBERT

for important keyword extraction,using KEYBERT algoritm

KEYBERT has count vectorizer which remove stopwords

cosine similarity to all embedding and give word accordingly in ascending or descending order

## 6.1 Install and Load KeyBERT

In [65]:
def search_and_summarize (query, k=5) :
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding, k)
  for score, idx in zip(D[0],I[0]):
    print ("Similarity score", score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"], max_length=120,min_length=40,do_sample=False)
    print(summary)
    print (summary[0]["summary_text"])
    print()

https://huggingface.co/learn/llm-course/en/chapter1/5

https://maartengr.github.io/KeyBERT/guides/countvectorizer.html

In [66]:
search_and_summarize("Deep Imaging in medical learning",k=5)

Similarity score 0.6995392
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.64733696
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

[{'summary_text': 'Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.'}]
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Similarity score 0.64072776
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

[{'summary_text': 'The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.'}]
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Similarity score 0.59748495
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

[{'summary_text': 'The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.'}]
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Similarity score 0.58939064
Title Self-paced Convolutional Neural Network for Computer Aided Detection in
  Medical Imaging Analysis
Title   Tissue characterization has long been an important component of Computer
Aided Diagnosis (CAD) systems for automatic lesion detection and further
clinical planning. Motivated by the superior performance of deep learning
methods on various computer vision problems, there has been increasing work
applying deep learning to medical image analysis. However, the development of a
robust and reliable deep learning model for computer-aided diagnosis is still
highly challenging due to the combination of

[{'summary_text': 'Tissue characterization has long been an important component of Computer \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0Aided Diagnosis (CAD) systems. Motivated by the superior performance of deep learningmethods on various computer vision problems, there has been increasing work applying deep learning to medical image analysis.'}]
Tissue characterization has long been an important component of Computer                Aided Diagnosis (CAD) systems. Motivated by the superior performance of deep learningmethods on various computer vision problems, there has been increasing work applying deep learning to medical image analysis.

keybert will take contextual meaning important words ,not repeating keywords

In [67]:
!pip install keybert==0.8.5

Collecting keybert==0.8.5
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.51.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.32.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.6.17)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Installing collected packages: keybert
Successfully installed keybert-0.8.5

In [68]:
from keybert import KeyBERT

## 6.2 Initialize KeyBERT Model

In [69]:
kw_model=KeyBERT()

In [70]:
type(kw_model)

keybert._model.KeyBERT

## 6.3 Test Keyword Extraction

automatically taking sentence trnasformer as model default as its just an algorithm and require a tranformer

In [71]:
text=df.iloc[10466]['abstract']
keywords=kw_model.extract_keywords(text)

In [72]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [73]:
print(type(keywords))

<class 'list'>

In [74]:
print(type(keywords[0]))

<class 'tuple'>

## 6.4 Integrate Keyword Extraction into Search and Summarize Function

In [75]:
kw_model.extract_keywords(text,keyphrase_ngram_range=(1,3),stop_words="english")

[('tomographic imaging deep', 0.6704),
 ('imaging deep learning', 0.6543),
 ('learning medical imaging', 0.6041),
 ('imaging deep', 0.5919),
 ('medical imaging', 0.5281)]

In [76]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [77]:
def search_and_summarize (query, k=5) :
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding, k)
  for score, idx in zip(D[0],I[0]):
    print ("Similarity score", score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"], max_length=120,min_length=40,do_sample=False)
    print(summary)
    print (summary[0]["summary_text"])
    print()
    kw_model.extract_keywords(text,keyphrase_ngram_range=(1,3),stop_words="english")
    print(keywords)
    for k,s in keywords:
      print(k)

# 7. Named Entity Recognition (NER) with GLiNER

In [78]:
search_and_summarize("Deep Imaging in medical learning",k=5)

Similarity score 0.6995392
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
imaging
tomographic
reconstruction
deep
learning
Similarity score 0.64733696
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

[{'summary_text': 'Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.'}]
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
imaging
tomographic
reconstruction
deep
learning
Similarity score 0.64072776
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

[{'summary_text': 'The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.'}]
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
imaging
tomographic
reconstruction
deep
learning
Similarity score 0.59748495
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

[{'summary_text': 'The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.'}]
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
imaging
tomographic
reconstruction
deep
learning
Similarity score 0.58939064
Title Self-paced Convolutional Neural Network for Computer Aided Detection in
  Medical Imaging Analysis
Title   Tissue characterization has long been an important component of Computer
Aided Diagnosis (CAD) systems for automatic lesion detection and further
clinical planning. Motivated by the superior performance of deep learning
methods on various computer vision problems, there has been increasing work
applying deep learning to medical image analysis. However, the development of a
robust and reliable deep learning model for computer-aided diagnosis is still
highly challenging due to the combination of

[{'summary_text': 'Tissue characterization has long been an important component of Computer \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0Aided Diagnosis (CAD) systems. Motivated by the superior performance of deep learningmethods on various computer vision problems, there has been increasing work applying deep learning to medical image analysis.'}]
Tissue characterization has long been an important component of Computer                Aided Diagnosis (CAD) systems. Motivated by the superior performance of deep learningmethods on various computer vision problems, there has been increasing work applying deep learning to medical image analysis.

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
imaging
tomographic
reconstruction
deep
learning

## 7.1 Langchain Tools Integration (Attempt)

more inclusion NER (named entity relationship)

In [79]:
pip install langchain-community langchain-core

Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.9.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (2.13.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.16.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.0)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 65.1 MB/s eta 0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 53.9 MB/s eta 0:00:00
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.0 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.0 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: requests, httpx-sse, pydantic-settings, langchain-text-splitters, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed httpx-sse-0.4.3 langchain-classic-1.0.8 langchain-community-0.4.2 langchain-text-splitters-1.1.2 pydantic-settings-2.14.2 requests-2.34.2

In [80]:
from langchain_core.tools import tool

@tool gives additonal feature to function without

## 7.2 Langchain HuggingFace Integration

In [81]:
@tool
def search_paper(quert:str)->str:
  "Search  research paper from the faiss database and return the most relevant result"

In [82]:
pip install langchain-huggingface

Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.36.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.4.8)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.21.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.34.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.9.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.13.4)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.16.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.1.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (4.14.0)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.7.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.16.0)
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Installing collected packages: langchain-huggingface
Successfully installed langchain-huggingface-1.2.2

In [83]:
from langchain_huggingface import HuggingFacePipeline

In [84]:
llm=HuggingFacePipeline(pipeline=summarizer)

## 7.3 Named Entity Recognition with GLiNER

we pipeline our code in hugging face so that automation can be done.

In [85]:
llm

HuggingFacePipeline(metadata={'lc_versions': {'langchain-core': '1.4.8', 'langchain': '1.3.11'}}, pipeline=<transformers.pipelines.text2text_generation.SummarizationPipeline object at 0x7d4b0a68d2b0>, model_id='facebook/bart-large-cnn')

In [86]:
response=llm.invoke("Breast cancer screening and longitudinal monitoring require imaging technologies that are portable, operator-independent, and suitable for frequent use, a capability not fully met by mammography or conventional ultrasound. We present a three-dimensional (3D) portable ultrasound system for real-time examination (3D PURE) that overcomes key limitations in volumetric breast imaging through advances in transducer design, acoustic materials, and adaptive beamforming. A box-array design incorporating a corner-gap offset geometry suppresses peak crosstalk (by 3.73 dB at the corner-most element), prevents preamplifier saturation, and supports higher transmit voltages (up to 24 V). A custom flowable backing layer (impedance 6.12 MRayl; attenuation 7.56 dB mm−1 MHz−1) integrates around fragile wirebonds, reduces inter-element crosstalk by ~4.5 dB throughout the array, and improves axial and lateral/elevational resolutions by ~200 µm and ~70 µm, respectively. Layered Aberration-Correction Reconstruction (LACR), an adaptive 3D beamformer, compensates for heterogeneous speed-of-sound (SoS) in the breast, reducing depth localization error by 2 mm and aberration defocusing by 70 µm on average at a 5 cm depth. Nine of the ten participants in an in vitro study showed improved microtarget detection efficiency with 3D PURE relative to a conventional 2D system (p = 0.0215), analogous to detection of microcalcifications. These results, combined with in vivo imaging validation of various phenotypes, highlight the potential of 3D PURE for reliable breast imaging. Furthermore, a vision-guided computer interface, MyFUS, ensures self-guided, user-friendly, and operator-independent probe positioning for longitudinal monitoring.")

In [87]:
print(response)

3D PURE overcomes key limitations in volumetric breast imaging through advances in transducer design, acoustic materials, and adaptive beamforming. A box-array design incorporating a corner-gap offset geometry suppresses peak crosstalk. Layered Aberration-Correction Reconstruction (LACR) compensates for heterogeneous speed-of-sound in the breast.

In [88]:
print(type(response))

<class 'str'>

In [89]:
!pip install gliner
from gliner import GLiNER

Collecting gliner
  Downloading gliner-0.2.27-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from gliner) (2.11.0+cpu)
Requirement already satisfied: transformers<5.7.0,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from gliner) (4.51.3)
Requirement already satisfied: huggingface_hub>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from gliner) (0.36.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gliner) (4.67.3)
Collecting onnxruntime (from gliner)
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from gliner) (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (2.34.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.1.6)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (2025.11.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (0.8.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (5.29.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->gliner) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->gliner) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.4->gliner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.4->gliner) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.4->gliner) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.4->gliner) (2026.6.17)
Downloading gliner-0.2.27-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.8/207.8 kB 9.2 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 47.1 MB/s eta 0:00:00
Installing collected packages: onnxruntime, gliner
Successfully installed gliner-0.2.27 onnxruntime-1.27.0

In [90]:
!pip install flashdeberta -U

Collecting flashdeberta
  Downloading flashdeberta-0.0.7-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: einops>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from flashdeberta) (0.8.2)
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from flashdeberta) (2.11.0+cpu)
Requirement already satisfied: transformers>=4.30.0 in /usr/local/lib/python3.12/dist-packages (from flashdeberta) (4.51.3)
Collecting triton>=3.0.0 (from flashdeberta)
  Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->flashdeberta) (2025.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (2.34.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.30.0->flashdeberta) (4.67.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers>=4.30.0->flashdeberta) (1.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.1.0->flashdeberta) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.1.0->flashdeberta) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.30.0->flashdeberta) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.30.0->flashdeberta) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.30.0->flashdeberta) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.30.0->flashdeberta) (2026.6.17)
Downloading flashdeberta-0.0.7-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.7/44.7 kB 2.1 MB/s eta 0:00:00
Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (197.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 7.2 MB/s eta 0:00:00
Installing collected packages: triton, flashdeberta
Successfully installed flashdeberta-0.0.7 triton-3.7.1

In [91]:
os.environ["USE_FLASHDEBERTA"] = "1"

## 7.4 Define NER Function

In [92]:
gliner_model = GLiNER.from_pretrained("knowledgator/gliner-decoder-base-v1.0")

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

pytorch_model.bin:   0%|          | 0.00/1.06G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

gliner_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/861 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

In [93]:
def NER_papers(abstract_list,result):
    labels = ["label"]

    for abstract in abstract_list:
        entities = gliner_model.predict_entities(abstract, labels, threshold=0.3, num_gen_sequences=1)

        extracted_data = []
        for entity in entities:
            extracted_data.append({
                "text": entity["text"],
                "label": entity["label"],
                "score": entity["score"]
            })
        result.append(extracted_data)
    return result

## 7.5 Define Search Function for Abstract List

In [94]:
def search_paper12(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  abstract=[]
  for score,idx in zip(D[0],I[0]):
    abstract.append(df.iloc[idx]["abstract"])
  return abstract

## 7.6 Execute Search and NER

In [95]:
abstract_list=search_paper12("Deep Imaging in medical learning",k=5)

In [96]:
for i in abstract_list:
  print(i)
  print()

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.


  Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.


  The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).


  Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.


  Tissue characterization has long been an important component of Computer
Aided Diagnosis (CAD) systems for automatic lesion detection and further
clinical planning. Motivated by the superior performance of deep learning
methods on various computer vision problems, there has been increasing work
applying deep learning to medical image analysis. However, the development of a
robust and reliable deep learning model for computer-aided diagnosis is still
highly challenging due to the combination of the high heterogeneity in the
medical images and the relative lack of training samples. Specifically,
annotation and labeling of the medical images is much more expensive and
time-consuming than other applications and often involves manual labor from
multiple domain experts. In this work, we propose a multi-stage, self-paced
learning framework utilizing a convolutional neural network (CNN) to classify
Computed Tomography (CT) image patches. The key contribution of this approach
is that we augment the size of training samples by refining the unlabeled
instances with a self-paced learning CNN. By implementing the framework on high
performance computing servers including the NVIDIA DGX1 machine, we obtained
the experimental result, showing that the self-pace boosted network
consistently outperformed the original network even with very scarce manual
labels. The performance gain indicates that applications with limited training
samples such as medical image analysis can benefit from using the proposed
framework.

In [97]:
result=[]

In [98]:
result=NER_papers(abstract_list,result)
show_progress_bar=True

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

In [99]:
type(result)

list

In [100]:
for i in result:
  print(i)

[{'text': 'tomographic imaging', 'label': 'label', 'score': 0.9443729519844055}, {'text': 'deep learning', 'label': 'label', 'score': 0.9661700129508972}, {'text': 'machine learning', 'label': 'label', 'score': 0.955564558506012}, {'text': 'image analysis', 'label': 'label', 'score': 0.8078495264053345}, {'text': 'image\nreconstruction', 'label': 'label', 'score': 0.834284245967865}, {'text': 'perspective article', 'label': 'label', 'score': 0.4489283263683319}, {'text': 'medical imaging', 'label': 'label', 'score': 0.8953460454940796}, {'text': 'image\nreconstruction', 'label': 'label', 'score': 0.7804543375968933}, {'text': 'domain knowledge', 'label': 'label', 'score': 0.5012676119804382}, {'text': 'big data', 'label': 'label', 'score': 0.8758136630058289}, {'text': 'innovative\napproaches', 'label': 'label', 'score': 0.37934067845344543}, {'text': 'image reconstruction', 'label': 'label', 'score': 0.859889566898346}, {'text': 'clinical and\npreclinical applications', 'label': 'label', 'score': 0.49080222845077515}, {'text': 'machine learning', 'label': 'label', 'score': 0.9309390783309937}, {'text': 'medical imaging', 'label': 'label', 'score': 0.9105990529060364}, {'text': 'major challenges', 'label': 'label', 'score': 0.5045690536499023}]
[{'text': 'deep convolutional neural network (CNN)', 'label': 'label', 'score': 0.66974937915802}, {'text': 'labeled training data', 'label': 'label', 'score': 0.7706490159034729}, {'text': 'expertise', 'label': 'label', 'score': 0.49542972445487976}, {'text': 'CNN', 'label': 'label', 'score': 0.5409672856330872}, {'text': 'labeled\nnatural images', 'label': 'label', 'score': 0.6038989424705505}, {'text': 'medical images', 'label': 'label', 'score': 0.3400707542896271}, {'text': 'medical image\nanalysis', 'label': 'label', 'score': 0.6363666653633118}, {'text': 'deep CNNs', 'label': 'label', 'score': 0.5021002888679504}, {'text': 'deep CNN', 'label': 'label', 'score': 0.5609955787658691}, {'text': 'radiology', 'label': 'label', 'score': 0.9430217742919922}, {'text': 'cardiology', 'label': 'label', 'score': 0.9378252625465393}, {'text': 'gastroenterology', 'label': 'label', 'score': 0.9631073474884033}, {'text': 'classification', 'label': 'label', 'score': 0.4350869953632355}, {'text': 'detection', 'label': 'label', 'score': 0.30127066373825073}, {'text': 'segmentation', 'label': 'label', 'score': 0.42393505573272705}, {'text': 'imaging\nmodalities', 'label': 'label', 'score': 0.3470114469528198}, {'text': 'deep CNNs', 'label': 'label', 'score': 0.5780068635940552}, {'text': 'pre-trained CNNs', 'label': 'label', 'score': 0.4379552900791168}, {'text': 'pre-trained CNN', 'label': 'label', 'score': 0.5099981427192688}, {'text': 'CNN', 'label': 'label', 'score': 0.48256295919418335}, {'text': 'fine-tuned CNNs', 'label': 'label', 'score': 0.48389732837677}, {'text': 'CNNs', 'label': 'label', 'score': 0.3743472993373871}, {'text': 'shallow tuning', 'label': 'label', 'score': 0.35404667258262634}, {'text': 'deep tuning', 'label': 'label', 'score': 0.3824489414691925}, {'text': 'layer-wise fine-tuning scheme', 'label': 'label', 'score': 0.3978416323661804}]
[{'text': 'MRI images', 'label': 'label', 'score': 0.7948366403579712}, {'text': 'anatomical field of view', 'label': 'label', 'score': 0.7089606523513794}, {'text': 'medical\nimages', 'label': 'label', 'score': 0.607553243637085}, {'text': 'deep learning', 'label': 'label', 'score': 0.8419196605682373}, {'text': 'computer vision', 'label': 'label', 'score': 0.43643519282341003}, {'text': 'AlexNet', 'label': 'label', 'score': 0.9499548077583313}, {'text': 'clinical use', 'label': 'label', 'score': 0.49231329560279846}, {'text': 'hyper-parameters', 'label': 'label', 'score': 0.7757883667945862}, {'text': 'architecture', 'label': 'label', 'score': 0.31449034810066223}, {'text': 'network', 'label': 'label', 'score': 0.4282301962375641}, {'text': 'exhaustive search', 'label': 'label', 'score': 0.41648566722869873}, {'text': 'network', 'label': 'label', 'score': 0.433126837015152}, {'text': 'random search', 'label': 'label', 'score': 0.7048839330673218}, {'text': 'adaptive search', 'label': 'label', 'score': 0.4580982029438019}, {'text': 'Gaussian Processes', 'label': 'label', 'score': 0.9155786037445068}, {'text': 'Probability of\nImprovement', 'label': 'label', 'score': 0.799467146396637}, {'text': 'MRI dataset', 'label': 'label', 'score': 0.5858843326568604}, {'text': 'baseline network', 'label': 'label', 'score': 0.7733764052391052}, {'text': 'final one', 'label': 'label', 'score': 0.501545250415802}, {'text': '20\\%', 'label': 'label', 'score': 0.44071027636528015}]
[{'text': 'deep learning', 'label': 'label', 'score': 0.8162832260131836}, {'text': 'natural images', 'label': 'label', 'score': 0.7952166795730591}, {'text': 'medical images', 'label': 'label', 'score': 0.8117796182632446}, {'text': 'deep convolutional neural\nnetwork', 'label': 'label', 'score': 0.7986485362052917}, {'text': 'medical image', 'label': 'label', 'score': 0.5080890655517578}, {'text': 'medical images', 'label': 'label', 'score': 0.716996967792511}, {'text': 'natural images', 'label': 'label', 'score': 0.6593836545944214}, {'text': 'coarse structures', 'label': 'label', 'score': 0.38539430499076843}, {'text': 'network architectures', 'label': 'label', 'score': 0.46586430072784424}, {'text': 'natural images', 'label': 'label', 'score': 0.6125655770301819}, {'text': 'heavily downscaled images', 'label': 'label', 'score': 0.4536339342594147}, {'text': 'memory requirements', 'label': 'label', 'score': 0.37848806381225586}, {'text': 'medical imaging', 'label': 'label', 'score': 0.4636634886264801}, {'text': 'multi-view deep\nconvolutional neural network', 'label': 'label', 'score': 0.6508905291557312}, {'text': 'medical\nimages', 'label': 'label', 'score': 0.5185673832893372}, {'text': 'large-scale mammography-based breast cancer screening', 'label': 'label', 'score': 0.3575570285320282}, {'text': 'BI-RADS prediction', 'label': 'label', 'score': 0.4197468161582947}, {'text': '886,000 images', 'label': 'label', 'score': 0.6735326051712036}, {'text': 'training set', 'label': 'label', 'score': 0.47219252586364746}, {'text': 'image size', 'label': 'label', 'score': 0.32746070623397827}, {'text': 'prediction accuracy', 'label': 'label', 'score': 0.374377578496933}, {'text': 'performance', 'label': 'label', 'score': 0.3866339325904846}, {'text': 'training set', 'label': 'label', 'score': 0.5090441107749939}, {'text': 'performance', 'label': 'label', 'score': 0.30719903111457825}, {'text': 'reader study', 'label': 'label', 'score': 0.5747203826904297}, {'text': 'random subset', 'label': 'label', 'score': 0.3750198185443878}, {'text': 'test set', 'label': 'label', 'score': 0.5022083520889282}, {'text': 'performance', 'label': 'label', 'score': 0.4440184533596039}, {'text': 'committee of\nradiologists', 'label': 'label', 'score': 0.610415518283844}]
[{'text': 'Tissue characterization', 'label': 'label', 'score': 0.6025040745735168}, {'text': 'Computer\nAided Diagnosis (CAD)', 'label': 'label', 'score': 0.6024250984191895}, {'text': 'automatic lesion detection', 'label': 'label', 'score': 0.5351337790489197}, {'text': 'clinical planning', 'label': 'label', 'score': 0.5097820162773132}, {'text': 'deep learning\nmethods', 'label': 'label', 'score': 0.5895317196846008}, {'text': 'computer vision problems', 'label': 'label', 'score': 0.3640250563621521}, {'text': 'deep learning', 'label': 'label', 'score': 0.40000155568122864}, {'text': 'medical image analysis', 'label': 'label', 'score': 0.8402125239372253}, {'text': 'deep learning', 'label': 'label', 'score': 0.43084874749183655}, {'text': 'computer-aided diagnosis', 'label': 'label', 'score': 0.5033718347549438}, {'text': 'medical images', 'label': 'label', 'score': 0.5059331059455872}, {'text': 'training samples', 'label': 'label', 'score': 0.6215816736221313}, {'text': 'annotation and labeling', 'label': 'label', 'score': 0.31548017263412476}, {'text': 'medical images', 'label': 'label', 'score': 0.5205051302909851}, {'text': 'manual labor', 'label': 'label', 'score': 0.4452537000179291}, {'text': 'domain experts', 'label': 'label', 'score': 0.3801833987236023}, {'text': 'multi-stage, self-paced\nlearning framework', 'label': 'label', 'score': 0.30613839626312256}, {'text': 'convolutional neural network (CNN)', 'label': 'label', 'score': 0.7877870798110962}, {'text': 'Computed Tomography (CT)', 'label': 'label', 'score': 0.8195124268531799}, {'text': 'training samples', 'label': 'label', 'score': 0.4712638258934021}, {'text': 'self-paced learning CNN', 'label': 'label', 'score': 0.4345003366470337}, {'text': 'high\nperformance computing servers', 'label': 'label', 'score': 0.6357287168502808}, {'text': 'NVIDIA DGX1 machine', 'label': 'label', 'score': 0.6884718537330627}, {'text': 'experimental result', 'label': 'label', 'score': 0.31508496403694153}, {'text': 'self-pace boosted network', 'label': 'label', 'score': 0.4760948121547699}, {'text': 'original network', 'label': 'label', 'score': 0.44690048694610596}, {'text': 'manual\nlabels', 'label': 'label', 'score': 0.3392804265022278}, {'text': 'training\nsamples', 'label': 'label', 'score': 0.3899506628513336}, {'text': 'medical image analysis', 'label': 'label', 'score': 0.8995228409767151}]

## 7.7 Spacy Integration

In [101]:
!pip install spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [102]:
import spacy

In [103]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 26.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [104]:
nlp = spacy.load('en_core_web_sm')

## 7.8 Define SpaCy NER Function

In [105]:
from collections import defaultdict

def NER_papers_spacy(abstract_list):
    spacy_results = []
    for abstract in abstract_list:
        doc = nlp(abstract)
        categorized_entities = defaultdict(list)
        for ent in doc.ents:
            categorized_entities[ent.label_].append(ent.text)
        spacy_results.append(dict(categorized_entities))
    return spacy_results

## 7.9 Demonstrate SpaCy NER Function

In [106]:
spacy_extracted_entities = NER_papers_spacy(abstract_list)
for doc_entities in spacy_extracted_entities:
    if doc_entities:
        print(doc_entities)
    else:
        print("No entities found for this abstract.")
    print()

No entities found for this abstract.

{'ORG': ['CNN', 'CNN', 'CNN', 'CNN', 'CNN'], 'CARDINAL': ['4', '3', '3', '1', '2', '3', '4']}

{'ORG': ['AlexNet', 'Gaussian Processes and Probability'], 'ORDINAL': ['first'], 'CARDINAL': ['20\\%']}

{'CARDINAL': ['886,000']}

{'ORG': ['Computer\nAided Diagnosis', 'CAD', 'CNN', 'Computed Tomography', 'CT', 'CNN']}

In [120]:
!pip install -qU langchain_groq

In [123]:
from langchain_groq import ChatGroq

In [114]:
from google.colab import userdata

In [145]:
api_key = userdata.get("groq_api_key")

In [146]:
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=api_key,
    temperature=0.7,
    timeout=30,
    max_tokens=1000
)

In [165]:
responses=llm.invoke("Hello, who are you?")

In [166]:
responses

AIMessage(content="Hello. I'm an artificial intelligence model, a computer program designed to simulate conversations and answer questions to the best of my knowledge. I'm here to help and provide information on a wide range of topics, from science and history to entertainment and culture. I can also assist with tasks such as language translation, text summarization, and more.\n\nI don't have a personal identity or emotions, but I'm designed to be helpful and engaging. I'm constantly learning and updating my knowledge base to provide more accurate and up-to-date information.\n\nWhat would you like to talk about or ask?", additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 118, 'prompt_tokens': 41, 'total_tokens': 159, 'completion_time': 0.165710869, 'completion_tokens_details': None, 'prompt_time': 0.002592886, 'prompt_tokens_details': None, 'queue_time': 0.051152476, 'total_time': 0.168303755}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_020e283281', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f414f-525b-75e3-a6d8-1987423f3ccd-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 41, 'output_tokens': 118, 'total_tokens': 159})

In [167]:
type(responses)

langchain_core.messages.ai.AIMessage

In [132]:
from langchain_core.tools import tool

In [150]:
@tool
def search_and_summarize(query: str, k: int = 5) -> str:
    """
    Search research papers from the FAISS database,
    retrieve the top-k most similar papers,
    summarize each paper using BART,
    and return the results.
    """

    query_embedding = model.encode([query])


    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    result = ""
    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):

        paper = df.iloc[idx]


        summary = summarizer(
            paper["abstract"],
            max_length=60, # Reduced max_length
            min_length=20, # Reduced min_length
            do_sample=False
        )[0]["summary_text"]

        result += f"Rank: {rank}\n"
        result += f"Similarity Score: {round(float(score),4)}\n"
        result += f"Title: {paper['title']}\n\n"

        result += "Abstract:\n"
        result += paper["abstract"][:500] + "...\n\n" # Truncated abstract

        result += summary + "\n\n"
    return result

In [151]:
tools = [search_and_summarize]

In [152]:
from langchain.agents import create_agent

In [159]:
agent= create_agent(
    model=llm,
    tools=tools
)

In [173]:
response = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": "Find the top 3 research papers on Vision Transformer."
            }
        ]
    }
)

In [171]:
responses.content

"Hello. I'm an artificial intelligence model, a computer program designed to simulate conversations and answer questions to the best of my knowledge. I'm here to help and provide information on a wide range of topics, from science and history to entertainment and culture. I can also assist with tasks such as language translation, text summarization, and more.\n\nI don't have a personal identity or emotions, but I'm designed to be helpful and engaging. I'm constantly learning and updating my knowledge base to provide more accurate and up-to-date information.\n\nWhat would you like to talk about or ask?"

In [174]:
response

{'messages': [HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='61909f86-b053-45b5-b34e-15577d506cc3'),
  AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'ahm35fwa5', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 24, 'prompt_tokens': 290, 'total_tokens': 314, 'completion_time': 0.033067153, 'completion_tokens_details': None, 'prompt_time': 0.022570726, 'prompt_tokens_details': None, 'queue_time': 0.006109852, 'total_time': 0.055637879}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f4165-7fcc-7363-8d46-58dbb52c0db3-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'ahm35fwa5', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 290, 'output_tokens': 24, 'total_tokens': 314}),
  ToolMessage(content='Rank: 1\nSimilarity Score: 0.4415\nTitle: Dense Transformer Networks\n\nAbstract:\n  The key idea of current deep learning methods for dense prediction is to\napply a model on a regular patch centered on each pixel to make pixel-wise\npredictions. These methods are limited in the sense that the patches are\ndetermined by network architecture instead of learned from data. In this work,\nwe propose the dense transformer networks, which can learn the shapes and sizes\nof patches from data. The dense transformer networks employ an encoder-decoder\narchitecture, and a pair of dense transformer modules are inserted into each of\nthe encoder and decoder paths. The novelty of this work is that we provide\ntechnical solutions for learning the shapes and sizes of patches from data and\nefficiently restoring the spatial correspondence required for dense prediction.\nThe proposed dense transformer modules are differentiable, thus the entire\nnetwork can be trained. We apply the proposed networks on natural and\nbiological image segmentation tasks and show superior performance is achieved\nin comparison to baseline methods.\n\n\nThe key idea of current deep learning methods for dense prediction is toapply a model on a regular patch centered on each pixel to make pixel-wisepredictions. These methods are limited in the sense that the patches are determined by network architecture instead of learned from data. In this work, we propose the dense transformer networks, which can learn the shapes and sizes of patches fromData.\n\nRank: 2\nSimilarity Score: 0.4169\nTitle: Inverse Compositional Spatial Transformer Networks\n\nAbstract:\n  In this paper, we establish a theoretical connection between the classical\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\nNetworks (STNs). STNs are of interest to the vision and learning communities\ndue to their natural ability to combine alignment and classification within the\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\nthan conventional STNs with less model capacity; in particular, we show\nsuperior performance in pure image alignment tasks as well as joint\nalignment/classification problems on real-world problems.\n\n\nIn this paper, we establish a theoretical connection between the classicalLucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs) STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework.\n\nRank: 3\nSimilarity Score: 0.4107\nTitle: gvnn: Neural Network Library for Geometric Computer Vision\n\nAbstract:\n  We introduce gvnn, a neural network library in Torch aimed towards bridging\nthe gap between classic geometric computer vision and deep learning. Inspired\nby the recent success of Spatial Transformer Networks, we propose several new\nlayers which are often used as parametric transformations on the data in\ngeometric computer vision. These layers can be inserted within a neural network\nmuch in the spirit of the original spatial transformers and allow\nbackpropagation to enable end-to-end learning of a network involving any domain\nknowledge in geometric computer vision. This opens up applications in learning\ninvariance to 3D geometric transformation for place recognition, end-to-end\nvisual odometry, depth estimation and unsupervised learning through warping\nwith a parametric transformation for image reconstruction error.\n\n\nWe introduce gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, we propose several new layers which are often used as parametric transformations on the data. These layers can be inserted within a neuralnetwork in the spirit of the original spatial transformers.\n\n', name='search_and_summarize', id='3b88975c-b3af-4e67-8af6-193c2fc830ad', tool_call_id='ahm35fwa5'),
  AIMessage(content="The function 'search_and_summarize' was called with the query 'Vision Transformer'. The function returned the top 3 research papers related to Vision Transformer, along with their titles and abstracts. The papers are:\n\n1. Dense Transformer Networks\n2. Inverse Compositional Spatial Transformer Networks\n3. gvnn: Neural Network Library for Geometric Computer Vision", additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 75, 'prompt_tokens': 1112, 'total_tokens': 1187, 'completion_time': 0.119519177, 'completion_tokens_details': None, 'prompt_time': 0.071691695, 'prompt_tokens_details': None, 'queue_time': 0.007072832, 'total_time': 0.191210872}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f4166-78a5-72b2-8965-6181e9b251b7-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1112, 'output_tokens': 75, 'total_tokens': 1187})]}

In [175]:
print(type(response))

<class 'dict'>

In [176]:

response["messages"][0]

HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='61909f86-b053-45b5-b34e-15577d506cc3')

In [177]:
response["messages"][1]

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'ahm35fwa5', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 24, 'prompt_tokens': 290, 'total_tokens': 314, 'completion_time': 0.033067153, 'completion_tokens_details': None, 'prompt_time': 0.022570726, 'prompt_tokens_details': None, 'queue_time': 0.006109852, 'total_time': 0.055637879}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f4165-7fcc-7363-8d46-58dbb52c0db3-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'ahm35fwa5', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 290, 'output_tokens': 24, 'total_tokens': 314})

In [178]:
response["messages"][2]

ToolMessage(content='Rank: 1\nSimilarity Score: 0.4415\nTitle: Dense Transformer Networks\n\nAbstract:\n  The key idea of current deep learning methods for dense prediction is to\napply a model on a regular patch centered on each pixel to make pixel-wise\npredictions. These methods are limited in the sense that the patches are\ndetermined by network architecture instead of learned from data. In this work,\nwe propose the dense transformer networks, which can learn the shapes and sizes\nof patches from data. The dense transformer networks employ an encoder-decoder\narchitecture, and a pair of dense transformer modules are inserted into each of\nthe encoder and decoder paths. The novelty of this work is that we provide\ntechnical solutions for learning the shapes and sizes of patches from data and\nefficiently restoring the spatial correspondence required for dense prediction.\nThe proposed dense transformer modules are differentiable, thus the entire\nnetwork can be trained. We apply the proposed networks on natural and\nbiological image segmentation tasks and show superior performance is achieved\nin comparison to baseline methods.\n\n\nThe key idea of current deep learning methods for dense prediction is toapply a model on a regular patch centered on each pixel to make pixel-wisepredictions. These methods are limited in the sense that the patches are determined by network architecture instead of learned from data. In this work, we propose the dense transformer networks, which can learn the shapes and sizes of patches fromData.\n\nRank: 2\nSimilarity Score: 0.4169\nTitle: Inverse Compositional Spatial Transformer Networks\n\nAbstract:\n  In this paper, we establish a theoretical connection between the classical\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\nNetworks (STNs). STNs are of interest to the vision and learning communities\ndue to their natural ability to combine alignment and classification within the\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\nthan conventional STNs with less model capacity; in particular, we show\nsuperior performance in pure image alignment tasks as well as joint\nalignment/classification problems on real-world problems.\n\n\nIn this paper, we establish a theoretical connection between the classicalLucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs) STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework.\n\nRank: 3\nSimilarity Score: 0.4107\nTitle: gvnn: Neural Network Library for Geometric Computer Vision\n\nAbstract:\n  We introduce gvnn, a neural network library in Torch aimed towards bridging\nthe gap between classic geometric computer vision and deep learning. Inspired\nby the recent success of Spatial Transformer Networks, we propose several new\nlayers which are often used as parametric transformations on the data in\ngeometric computer vision. These layers can be inserted within a neural network\nmuch in the spirit of the original spatial transformers and allow\nbackpropagation to enable end-to-end learning of a network involving any domain\nknowledge in geometric computer vision. This opens up applications in learning\ninvariance to 3D geometric transformation for place recognition, end-to-end\nvisual odometry, depth estimation and unsupervised learning through warping\nwith a parametric transformation for image reconstruction error.\n\n\nWe introduce gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, we propose several new layers which are often used as parametric transformations on the data. These layers can be inserted within a neuralnetwork in the spirit of the original spatial transformers.\n\n', name='search_and_summarize', id='3b88975c-b3af-4e67-8af6-193c2fc830ad', tool_call_id='ahm35fwa5')